"""시스템의 내부에서 일어나는 에러를 다룸."""

from .exception_handler import custom_exception_handler as custom_exception_handler
